// THE STANDING SIGNAL (2026-09-05). The email can be missed — one was, and
// a worker has been waiting since 2026-08-31 because of it. The roster is
// the place a person looks when they think about their workers, so it has
// to be the place that says which ones want them, and it has to keep
// saying it until they answer.
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { LabWaiting, waitedFor } from '@/components/lab-waiting';

const NOW = new Date('2026-09-05T00:00:00Z');
const WAITING = [
  {
    runId: 'run-abc',
    harnessHash: 'h1',
    harnessName: 'analyze-data-file-with-totals-chart-and-summary',
    question: 'Should I use the 2024 sheet or the 2025 one?',
    since: '2026-08-31T00:00:00Z',
  },
];

describe('LabWaiting', () => {
  it('draws nothing at all when nothing is waiting', () => {
    expect(renderToStaticMarkup(<LabWaiting waiting={[]} />)).toBe('');
  });

  it('leads with the QUESTION, because that is the answerable part', () => {
    const html = renderToStaticMarkup(<LabWaiting waiting={WAITING} />);
    const q = html.indexOf('Should I use the 2024 sheet');
    const name = html.indexOf('analyze-data-file-with-totals');
    expect(q).toBeGreaterThan(-1);
    // "<auto-generated-name> needs a decision" tells a reader nothing they
    // can act on; the question tells them everything.
    expect(q).toBeLessThan(name);
  });

  it('links straight to the run, so answering is one click', () => {
    expect(renderToStaticMarkup(<LabWaiting waiting={WAITING} />)).toContain('href="/lab/run/run-abc"');
  });

  it('a worker with no recorded question still gets a line', () => {
    const html = renderToStaticMarkup(<LabWaiting waiting={[{ ...WAITING[0]!, question: null }]} />);
    expect(html).toContain('needs a decision from you');
  });

  it('counts correctly, singular and plural', () => {
    expect(renderToStaticMarkup(<LabWaiting waiting={WAITING} />)).toContain('a worker is waiting for you');
    const two = renderToStaticMarkup(
      <LabWaiting waiting={[WAITING[0]!, { ...WAITING[0]!, runId: 'run-def' }]} />,
    );
    expect(two).toContain('2 workers are waiting for you');
  });
});

describe('waitedFor', () => {
  it('is the roughest honest unit — "5 days" is the fact that matters', () => {
    expect(waitedFor('2026-08-31T00:00:00Z', NOW)).toBe('5 days');
    expect(waitedFor('2026-09-04T22:00:00Z', NOW)).toBe('2 hours');
    expect(waitedFor('2026-09-04T23:30:00Z', NOW)).toBe('30 minutes');
    expect(waitedFor('2026-09-04T23:00:00Z', NOW)).toBe('1 hour'); // singular
  });

  it('never reads as a negative or a nonsense duration', () => {
    expect(waitedFor('2026-09-05T00:00:00Z', NOW)).toBe('just now');
    expect(waitedFor('2027-01-01T00:00:00Z', NOW)).toBe('just now'); // clock skew
    expect(waitedFor('not a date', NOW)).toBe('just now');
  });
});
