// ESLint flat config — typescript-eslint, minimal sane rules (SPEC §0/§11).
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      // Stale worktree copies of THIS repo (agent sessions). Without this, every
      // problem in the real tree is reported once per worktree — 36 errors where
      // there are 8 (found 2026-09-03).
      '**/.claude/**',
      '**/coverage/**',
      '**/.next/**',
      '**/drizzle/**',
      // Generated by `next build` ("This file should not be edited") — next
      // 15.5 adds a triple-slash routes.d.ts reference we cannot restyle.
      '**/next-env.d.ts',
    ],
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      // SPEC interfaces use `any` in a few handler signatures (e.g. queue).
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'warn',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },
  {
    files: ['**/*.test.ts', 'scripts/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
