// The prose of /docs (app/docs/page.tsx), flattened to plain text so
// /api/docs-ask can answer from it and nothing else. Keep this in step with
// the page: when a section there changes, change it here. Kept under ~8k
// characters on purpose — it rides in the system prompt of every question.
export const DOCS_TEXT = `Potion is a measured model router with an OpenAI-compatible API. It speaks the OpenAI chat-completions protocol: if you already have an OpenAI client you change one line (the base URL and key) and keep everything else. The request body, the response shape, streaming and tool calls are unchanged.

QUICKSTART. 1. Create a serving key on the API keys page (/settings/keys). 2. Point your client at the base URL, https://api.withpotion.com/v1. 3. Send a request; it appears on Connect with the routing decision it got. With curl or the openai SDK (Node or Python), use the base URL, a bearer key read from POTION_API_KEY, and model "potion-auto". The page also has copyable instruction blocks for coding agents; the key is never in the block.

AUTHENTICATION. Every call carries a serving key as a bearer token: Authorization: Bearer $POTION_API_KEY. Keys come in two scopes. A "serve" key sends traffic and reads its own state; "serve+admin" is additionally allowed to provision (mint keys, move budgets, rebind policy). A key is shown once, at creation, and stored only as a SHA-256 hash; if it is lost, revoke it and mint another. Each key carries its own policy binding, so separate keys run different trade-offs side by side. You do not bring provider keys; Potion serves every request from its own, across providers.

THE MODEL FIELD MEANS WHAT IT SAYS. Three cases: "potion-auto" ROUTES (Potion classifies the request and serves the measured pick under your policy). A KNOWN model name PINS: exactly that model answers, the trace says policy=pinned, nothing overrides your explicit choice. An UNKNOWN name is a 400 unknown_model error, never a silent reroute. Migration mode (Settings · Controls, or PUT /api/org-settings, admin) makes every label route like potion-auto — an explicit org-level choice for apps whose model strings cannot change yet. The receipt always names what actually answered.

RECEIPTS AND THE KEPT LINE. Every served request becomes a row on the Receipts page: when it ran, the kind of work, the model that answered (also in the x-potion-model response header and the served_model log field), what it cost, and what your named baseline WOULD have cost — recorded at serve time from real token counts, never reconstructed. The difference is the "kept" line; the month's kept lines sum to the savings figure on Today. GET /api/routing-activity returns the rows programmatically, including servedModel and baselineCostUsd.

YOUR BAR, YOUR FLOOR, YOUR PINS. Name what you use today with PUT /api/incumbents (admin) and your quality bar becomes a measurement against your own model on your own traffic. Potion samples consented requests (capped per kind of work, personal data redacted), measures, and proposes your bar; the proposal appears on Today and applies in one click via POST /api/learning/proposals/:id/apply. PUT /api/floor sets the org-wide quality floor and rebinds every live key. GET/PUT/DELETE /api/pins/:clusterId freezes or releases the frontier version serving a workload, and GET /api/frontier-changelog narrates every movement in plain English, including what a pin is holding back.

PRICING, ALIGNED BY CONSTRUCTION. Model costs pass through at cost; Potion's revenue is a share of the savings your receipts verify (the serve-time counterfactual, summed per period). If Potion saves you nothing it earns nothing above cost. GET /api/usage/invoice itemises model cost, verified savings, and the share.

AGENT JOURNEYS. Agent workloads send spans to POST /v1/traces with the same bearer key; Potion prices every span, flags tool-call loops, and clusters redacted sessions into agent-* workloads with their own frontiers. Pin a request to a cluster explicitly with the X-Potion-Cluster header. PUT /api/traces/retention sets span retention in days; 0 keeps metadata only, with prompts and attributes redacted on purge.

THE DECISION HEADER. Every response carries x-frontier-trace, the routing decision in full, on every request rather than behind a debug flag. Example: cluster=code-gen;strategy=6efe8a56;frontier=v2;policy=min_cost;fallback=0;provenance=live. cluster: the workload type the prompt was classified into. strategy: first 8 characters of the selected strategy hash, the exact configuration served. frontier: the published frontier version the choice came from; it increments when new evidence republishes. policy: the rule that selected the point. fallback: 0 means your policy selected a point on a measured frontier; 1 means none existed and the request rode the default strategy, the honest signal that Potion has nothing measured for this work yet. provenance: live means the evidence behind the choice came from real provider runs; anything else should not be treated as a measurement. constrained=tools appears when a request carrying tools was narrowed to single-model points; the policy's bound still held and fallback stays 0.

POLICIES. A policy is the rule Potion optimises under, bound per key, applied to every request that key sends. min_cost: cheapest option holding a quality floor. max_quality: best measured quality under a cost ceiling. latency_bound: best quality inside a p95 latency budget. compound: a quality floor and a latency bound, cheapest of the survivors. Cost ceilings are per 1,000 requests, not per 1,000 tokens. Latency bounds are p95 in milliseconds. Rebind a key's policy with POST /v1/policies, for example {"type":"min_cost","qualityFloor":0.8}.

WORKLOAD TYPES. Every prompt is classified before anything is selected; each type has its own frontier: code-gen, code-review, extraction, summarization, classification, multi-step-reasoning, creative, rewrite-edit, rag-answer, agentic-tool-use. A prompt matching none confidently is served on the default strategy and the trace says fallback=1.

STREAMING AND COMPATIBILITY. Set stream: true and you get standard server-sent events terminated by data: [DONE]. The routing decision is chosen before the first token, so x-frontier-trace is on the response headers even while the body is still streaming. Tools and function calling pass through unchanged; a request carrying tools is served from a single-model point, and if that was not the policy's optimum the trace says constrained=tools. Token usage and cost come back on the response from the provider's own figures. Legacy completions are shimmed at /v1/completions.

ERRORS use the OpenAI envelope { error: { message, type, param, code } }. 400 invalid_request_error: the body did not validate. 400 unknown_model: the model value is neither potion-auto nor a model Potion serves. 400 cluster_not_found: an explicit X-Potion-Cluster hint named a cluster that does not exist. 401 authentication_required: no bearer token. 401 invalid_api_key: unknown, revoked or expired key. 403 insufficient_role: the call needs admin. 413: body too large. 429 rate_limit_exceeded: too many requests, back off and retry. 429 budget_exceeded: your spend cap would be crossed; refused BEFORE the provider is called, so it costs nothing. 503 service_unavailable: no upstream could serve the request.

LIMITS AND BUDGETS. A budget is a cap on spend with an optional hard stop, checked before the upstream call, so a refused request costs nothing. Set it on Usage or through /api/budgets. Rate limits are enforced per key; treat 429 as backpressure rather than failure.

API REFERENCE. POST /v1/chat/completions: serve a request, streaming supported. POST /v1/completions: legacy shim. POST /v1/embeddings: platform embedder. GET /v1/models: the catalogue, with potion.measured marking what is routable. GET/POST /v1/policies: read or rebind the calling key's policy. POST /v1/traces: agent spans in. Dashboard reads and provisioning, same bearer token: POST /api/plan, GET /api/connection, GET /api/routing-activity, GET/POST /api/api-keys (minting needs serve+admin), GET/PUT /api/budgets, GET /api/usage (+ /current, /invoice), PUT /api/incumbents, GET /api/learning (+ proposals apply), PUT /api/floor, GET/PUT/DELETE /api/pins/:clusterId, GET /api/frontier-changelog, GET /api/certifications, GET/PUT /api/org-settings, GET/PUT /api/traces/retention, GET /api/audit (+ export.jsonl).

THINGS WORTH KNOWING. A catalogue is not a frontier: only points measured for your kind of work are selected automatically. Quality numbers carry confidence intervals; strategies that overlap inside the interval are reported as tied and your policy decides on cost or latency. Latency starts provisional (p95 from evaluation runs) and switches to serving-grade latency measured on your own requests once there is enough traffic. Your first requests route on platform evidence, measurements of the workload type rather than of you; as your traffic accumulates the numbers become yours.`;
