// The prose of /docs (app/docs/page.tsx), flattened to plain text so
// /api/docs-ask can answer from it and nothing else. Keep this in step with
// the page: when a section there changes, change it here. Kept under ~6k
// characters on purpose — it rides in the system prompt of every question.
export const DOCS_TEXT = `Potion is a measured model router with an OpenAI-compatible API. It speaks the OpenAI chat-completions protocol: if you already have an OpenAI client you change one line (the base URL and key) and keep everything else. The request body, the response shape, streaming and tool calls are unchanged.

QUICKSTART. 1. Create a serving key on the API keys page (/settings/keys). 2. Point your client at the base URL, https://api.withpotion.com/v1. 3. Send a request; it appears on Connect with the routing decision it got. With curl or the openai SDK (Node or Python), use the base URL, a bearer key read from POTION_API_KEY, and model "potion-auto". The page also has copyable instruction blocks for coding agents; the key is never in the block.

AUTHENTICATION. Every call carries a serving key as a bearer token: Authorization: Bearer $POTION_API_KEY. Keys come in two scopes. A "serve" key sends traffic and reads its own state; "serve+admin" is additionally allowed to provision (mint keys, move budgets, rebind policy). A key is shown once, at creation, and stored only as a SHA-256 hash; if it is lost, revoke it and mint another. Each key carries its own policy binding, so separate keys run different trade-offs side by side. You do not bring provider keys; Potion serves every request from its own, across providers.

THE MODEL FIELD IS A LABEL, NOT A CHOICE. Potion reads each request, works out which kind of work it is, and selects a strategy from the measured frontier under your policy. Whatever you put in "model" is echoed back and recorded, and is NOT an input to that decision. "potion-auto" is the documented convention; sending a specific model id will not pin it.

THE DECISION HEADER. Every response carries x-frontier-trace, the routing decision in full, on every request rather than behind a debug flag. Example: cluster=code-gen;strategy=6efe8a56;frontier=v2;policy=min_cost;fallback=0;provenance=live. cluster: the workload type the prompt was classified into. strategy: first 8 characters of the selected strategy hash, the exact configuration served. frontier: the published frontier version the choice came from; it increments when new evidence republishes. policy: the rule that selected the point. fallback: 0 means your policy selected a point on a measured frontier; 1 means none existed and the request rode the default strategy, the honest signal that Potion has nothing measured for this work yet. provenance: live means the evidence behind the choice came from real provider runs; anything else should not be treated as a measurement. constrained=tools appears when a request carrying tools was narrowed to single-model points; the policy's bound still held and fallback stays 0.

POLICIES. A policy is the rule Potion optimises under, bound per key, applied to every request that key sends. min_cost: cheapest option holding a quality floor. max_quality: best measured quality under a cost ceiling. latency_bound: best quality inside a p95 latency budget. compound: a quality floor and a latency bound, cheapest of the survivors. Cost ceilings are per 1,000 requests, not per 1,000 tokens. Latency bounds are p95 in milliseconds. Rebind a key's policy with POST /v1/policies, for example {"type":"min_cost","qualityFloor":0.8}.

WORKLOAD TYPES. Every prompt is classified into one of these before anything is selected; each has its own frontier. code-gen: writing code to a specification. code-review: finding defects in code. extraction: pulling structured fields out of unstructured documents. summarization: condensing a document while preserving what matters. classification: assigning a label from a fixed set. multi-step-reasoning: problems needing several dependent steps. creative: open-ended writing with no single right answer. rewrite-edit: revising text to a brief without changing its meaning. rag-answer: answering from supplied source passages. agentic-tool-use: planning and sequencing tool calls. A prompt that matches none of them confidently is served on the default strategy and the trace says fallback=1.

STREAMING AND COMPATIBILITY. Set stream: true and you get standard server-sent events terminated by data: [DONE]. The routing decision is chosen before the first token, so x-frontier-trace is on the response headers even while the body is still streaming. Tools and function calling pass through unchanged; a request carrying tools is served from a single-model point, and if that was not the policy's optimum the trace says constrained=tools. Token usage and cost come back on the response from the provider's own figures. Legacy completions are shimmed at /v1/completions.

ERRORS use the OpenAI envelope { error: { message, type, param, code } }. 400 invalid_request_error: the body did not validate. 401 authentication_required: no bearer token. 401 invalid_api_key: unknown, revoked or expired key. 403: the key's scope does not cover this call. 413: body too large. 429 rate_limit_exceeded: too many requests, back off and retry. 429 budget_exceeded: your spend cap would be crossed; refused BEFORE the provider is called, so it costs nothing. 503 service_unavailable: no upstream could serve the request.

LIMITS AND BUDGETS. A budget is a cap on spend with an optional hard stop, checked before the upstream call, so a refused request costs nothing. Set it on Usage or through /api/budgets. Rate limits are enforced per key; treat 429 as backpressure rather than failure.

API REFERENCE. POST /v1/chat/completions: serve a request, streaming supported. POST /v1/completions: legacy shim. POST /v1/embeddings: platform embedder. GET /v1/models: the catalogue, with potion.measured marking what is routable. GET/POST /v1/policies: read or rebind the calling key's policy. Dashboard reads and provisioning: POST /api/plan (workload type and measured options for what you are building), GET /api/connection, GET /api/routing-activity, GET/POST /api/api-keys (minting needs serve+admin), GET/PUT /api/budgets, GET /api/usage; all take the same bearer token.

THINGS WORTH KNOWING. A catalogue is not a frontier: only points measured for your kind of work are selected automatically. Quality numbers carry confidence intervals; strategies that overlap inside the interval are reported as tied and your policy decides on cost or latency. Latency starts provisional (p95 from evaluation runs) and switches to serving-grade latency measured on your own requests once there is enough traffic. Your first requests route on platform evidence, measurements of the workload type rather than of you; as your traffic accumulates the numbers become yours.`;
