import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/legal';
import { SiteShell } from '@/components/site-header';

export const metadata: Metadata = { title: 'Terms of Service — Potion' };

export default function TermsPage() {
  return (
    <SiteShell>
      <LegalPage title="Terms of Service" updated="August 24, 2026">
        <LegalSection heading="What Potion is">
          <p>
            Potion is an API and dashboard operated by Mutiny (&ldquo;we&rdquo;). You send requests to an
            OpenAI-compatible endpoint; we route each request to a third-party AI model chosen from
            measurements of quality and cost, and return the model&rsquo;s answer. By creating an account or
            using the API you agree to these terms on behalf of yourself or the organization you represent.
          </p>
        </LegalSection>

        <LegalSection heading="Your account and keys">
          <p>
            Sign-in is by email link; there are no passwords. Admins can invite teammates with a role, and
            you are responsible for who you invite. API keys act on behalf of your organization: keep them
            secret, and everything requested under your keys is your usage. If a key leaks, revoke it in the
            dashboard — we store only a hash, so we cannot recover a lost key, only replace it.
          </p>
        </LegalSection>

        <LegalSection heading="Fees">
          <p>
            Pricing is usage-based: you pay for the requests we serve, measured in tokens, at the prices
            shown in the dashboard. If you opt in to workload measurement, those measurement runs are billed
            to your organization at cost, under a daily cap. Prices can change; we will tell you before a
            change applies to you.
          </p>
        </LegalSection>

        <LegalSection heading="Acceptable use">
          <p>
            Use the service lawfully. Don&rsquo;t probe or break tenant isolation, resell access without our
            written agreement, or use the API in ways the underlying model providers prohibit — their
            acceptable-use rules travel with their models, and your requests must comply with them.
          </p>
        </LegalSection>

        <LegalSection heading="Your content, third-party models">
          <p>
            Your prompts and the answers you receive are yours. You give us only the rights needed to
            operate the service: to pass your request to the model that serves it and to return the answer.
            We do not train models on your content. Answers are generated by third-party models we do not
            control; our quality figures are measurements on defined test suites, not a promise about any
            single answer, and nothing here is professional advice.
          </p>
        </LegalSection>

        <LegalSection heading="Availability">
          <p>
            We work to keep the service up and monitored, but unless we have signed a separate agreement
            with you, the service is provided as-is, without a warranty of uninterrupted availability.
          </p>
        </LegalSection>

        <LegalSection heading="Liability">
          <p>
            To the extent the law allows, our total liability for claims arising from the service is capped
            at the amount you paid us in the twelve months before the claim, and neither of us is liable to
            the other for indirect or consequential damages.
          </p>
        </LegalSection>

        <LegalSection heading="Ending things">
          <p>
            You can stop using the service at any time and ask us to delete your organization, which removes
            your data as described in the <a className="underline decoration-[#b8b3a6] underline-offset-2 hover:decoration-ink" href="/privacy">Privacy Policy</a>. We can suspend or end access for breach of
            these terms, and will tell you why.
          </p>
        </LegalSection>

        <LegalSection heading="Changes">
          <p>
            We may update these terms; material changes will be announced by email or in the dashboard
            before they take effect. This draft has not yet completed legal review; the reviewed version
            will also name the contracting entity&rsquo;s legal form and the governing law.
          </p>
        </LegalSection>
      </LegalPage>
    </SiteShell>
  );
}
